### ISSUE TITLE
new home for cli-wg?

### ISSUE THREAD

**Issue by bosr** [rust-cli/book#1]
Hi,

I'm missing the cli-wg that was available at rust-lang-nursery. It was pulled about 24h hours ago, since then cli-wg is not available anywhere.

Is this repo the next home for it? 

Thanks

**Comment by epage** [comment]
The repo was split between this one and [meta](https://github.com/rust-cli/meta/issues)

**Comment by bosr** [comment]
Thanks, so the book is now available at https://rust-cli.github.io/meta/

Just fyi, most of the links on the main page https://www.rust-lang.org/what/cli still point to the previous address.
