### ISSUE TITLE
References to Cargo.toml in Testing chapter are wrong

### ISSUE THREAD

**Issue by daniel-svard** [rust-cli/book#100]
The references to Cargo.toml in sections "Testing CLI applications by running them" and "Generating test files" reference the wrong lines in `src/tutorial/testing/Cargo.toml`. They should reference lines from the `dev-dependencies` section, but instead reference lines from the `dependencies` section.

**Comment by epage** [comment]
Thanks! I've got a fix prepared.

I wish there was a better way to verify that changing the included content doesn't unintentionally change the book
