### ISSUE TITLE
Error expectation in "Testing CLI applications by running them" is slightly wrong.

### ISSUE THREAD

**Issue by nth-Jellyfish** [rust-cli/book#101]
The expected error line reads `.stderr(predicate::str::contains("could not read file"));`, but for me this resulted in a test failure since my actual error output is "Error: can't read file test/file/doesnt/exist". When I changed the line to `.stderr(predicate::str::contains("can't read file"));` the test passes.

**Comment by epage** [comment]
Could you include your `main.rs`?  It sounds like you wrote a different error output than what the book described which means you'd have to test for different output.

**Comment by nth-Jellyfish** [comment]
Oh you are totally right, I am foolish. mb
