### ISSUE TITLE
Initial example Clap implementation has deprecation warnings - Command Line Applications In Rust

### ISSUE THREAD

**Issue by ConnorJamesLow** [rust-cli/book#147]
I am following the _Command Line Applications In Rust_ tutorial using Rust 2021 edition. The book contains the following code:

```rs
#![allow(unused)]

use clap::Parser;

/// Search for a pattern in a file and display the lines that contain it.
#[derive(Parser)]
struct Cli {
    /// The pattern to look for
    pattern: String,
    /// The path to the file to read
    #[clap(parse(from_os_str))]
    path: std::path::PathBuf,
}

fn main() {
    let args = Cli::parse();
}
```

Which produces the following warnings:

![image](https://user-images.githubusercontent.com/37132524/173412446-734e68fc-00a7-42aa-84ad-128415f21a9f.png)

Possible solutions: 

- Update the book to use non-deprecated code.
- Else, if this was at one time stable, provide more specific versioning for Clap and Rust (adding the dependency according to the guide gave me clap v3.2.1).

**Comment by epage** [comment]
See also https://github.com/clap-rs/clap/issues/3822
