### ISSUE TITLE
2.5 "How to deal with input piped to ss"

### ISSUE THREAD

**Issue by DesmondWillowbrook** [rust-cli/book#16]
TODO still points to old github page, which now leads to a 404.

![image](https://user-images.githubusercontent.com/51814158/94118782-9d2ab900-fe6b-11ea-88d0-e8c979b35d0d.png)

[Link](https://rust-cli.github.io/book/in-depth/machine-communication.html#how-to-deal-with-input-piped-into-us)

**Comment by michelk** [comment]
It would be great to have an example cli-program with usage: 
```
sample-program --output <optional-output-file> <optional-input-file>
```
if `--output` is missing, output will be written to stdout; if `input-file` is missing, input is read from stdin. 

Thanks.

**Comment by michelk** [comment]
The above mentioned feature-request should go into section 1.2. Therefor I opened a new issue #36

**Comment by DesmondWillowbrook** [comment]
Closing in favor of #36
