### ISSUE TITLE
TIP: new version of clap

### ISSUE THREAD

**Issue by Narven** [rust-cli/book#168]
if someone is using:

```toml
clap = "3.2.22"
```

```rust
Arg::with_name("omit_newline")
            .short('n')
            .help("Do not print newline")
            .takes_value(false),
        )
```

`short` no longer accepts `&str`, it needs to be `char`, so just replace it with single quotes `'n'`.

**Comment by epage** [comment]
Yes, this changed with clap 3.0.0.

In case there is a question, the Book is updated to reflect these changes.

btw the release candidate for 4.0.0 is out right now.
