### ISSUE TITLE
Add appendix of relevant crates

### ISSUE THREAD

**Issue by sburris0** [rust-cli/book#24]
I think it would be helpful to list some useful CLI crates in an appendix including those used in the book.

**Comment by killercup** [comment]
PR welcome! Adding the ones mentioned in the book with some comment would be a great start. I would be hesitant to make this too extensive as it can quickly become outdated. It needs to offer a significant benefit over a page like https://lib.rs/command-line-interface or one of the blog posts that people post about this topic every couple of months :)

**Comment by sburris0** [comment]
Just made a PR with a list of crates used in the book and a list of relevant lib.rs categories

**Comment by Dylan-DPC** [comment]
Generally we didn't want to add crates to the book because we didn't want to be biased towards certain crates. But i guess this is fine
