### ISSUE TITLE
Links still pointing to https://github.com/rust-lang-nursery/cli-wg

### ISSUE THREAD

**Issue by theoamonteiro** [rust-cli/book#3]
Thanks! So the book is now available at https://rust-cli.github.io/meta/

Just fyi, most of the links on the main page https://www.rust-lang.org/what/cli still point to the previous address.

_Originally posted by @bosr in https://github.com/rust-cli/book/issues/1#issuecomment-562880961_

**Comment by epage** [comment]
Looks like this is resolved
