### ISSUE TITLE
The usage of the signal-hook seems to be an old version

### ISSUE THREAD

**Issue by starkbobo** [rust-cli/book#33]
I've tried to follow [the signal-hook’s example in the book](https://github.com/rust-cli/book/blob/master/src/in-depth/signals-hooked.rs), but it didn't compile.
The error info: `error[E0432]: unresolved import signal_hook::SIGINT`.
My rustc version is `1.52.1` and the signal-hook is `0.3.9`

I checked the official website of the signal hook and it seems that the usage in the example is not compatible in my version
I try to fix it simply, that's my answer
```rust
use signal_hook::{iterator::Signals, consts};
use std::{error::Error, thread, time::Duration};

fn main() -> Result<(), Box<dyn Error>> {
    let mut signals = Signals::new(&[consts::SIGINT])?;
    thread::spawn(move || {
        for sig in signals.forever() {
            println!("Received signal {:?}", sig);
        }
    });

    // Following code does the actual work, and can be interrupted by pressing
    // Ctrl-C. As an example: Let's wait a few seconds.
    thread::sleep(Duration::from_secs(2));

    Ok(())
}
```

**Comment by epage** [comment]
I think this is the relevant section of the changelog
https://github.com/vorner/signal-hook/blob/master/CHANGELOG.md#030

**Comment by epage** [comment]
The book should now be updated
