### ISSUE TITLE
Suggestion: add GitHub Actions example

### ISSUE THREAD

**Issue by trevordmiller** [rust-cli/book#50]
It would be helpful to have a GitHub Actions example to go along with the Travis CI / Trust items in https://rust-lang-nursery.github.io/cli-wg/tutorial/packaging.html.

**Comment by jpmckinney** [comment]
The documentation already has links to projects that contain GitHub Actions examples, but they are all deprecated or abandoned.

* trust is [abandoned](https://github.com/japaric/trust/issues/136) and [doesn't work on GitHub Actions](https://github.com/japaric/trust/issues/125).
* wasm-pack (there are links to its Travis and Appveyor files, but it also [uses GitHub Actions now](https://github.com/rustwasm/wasm-pack/blob/master/.github/workflows/release.yml)) uses set-output, which is deprecated, uses actions-rs/toolchain, which is [unmaintained](https://github.com/actions-rs/toolchain/issues/216) (use dtolnay/rust-toolchain instead), and uses actions/create-release and actions/upload-release-asset, which are archived and use set-output.
* ripgrep ([uses GitHub Actions now](https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml)) uses an old, strange GITHUB_REF workaround (use github.ref_name or GITHUB_REF_NAME), and uses actions/create-release and actions/upload-release-asset (see above).

The best way to do things now on GitHub Actions is very simple:

* Use `${{ github.ref_name }}` (or `$GITHUB_REF_NAME`)
* Use [cross](https://github.com/cross-rs/cross)
* Use the [GitHub CLI](https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows) in GitHub Actions workflows
 
Example: https://github.com/open-contracting/cardinal-rs/blob/main/.github/workflows/release.yml
