### ISSUE TITLE
Book: Testing.md code block not updated

### ISSUE THREAD

**Issue by c1gallagher** [rust-cli/book#98]
![Testing_page](https://user-images.githubusercontent.com/90812488/144947594-64b1a2e4-f641-4bb7-bca9-e9946a54d400.PNG)

It looks like the book's Testing page isn't displaying the updated code from the testing/tests/cli.rs file, which was updated with #19. The displayed code shows the old error string in the example, which fails testing. 

![Tests_code](https://user-images.githubusercontent.com/90812488/144948073-e40864a9-6ae3-452d-8e35-bdf4012d3e32.PNG)
![Book_code](https://user-images.githubusercontent.com/90812488/144948161-d47f8d48-9610-4163-ad14-c55ed1b1db36.PNG)

**Comment by epage** [comment]
Thanks for reporting this!

My guess is that the travis deployment isn't working anymore.  We should get it switched over to GH Actions.

**Comment by epage** [comment]
If I'm reading this report correctly, it looks like our GH Actions deployment was a success and we now have the new version posted.

Can you verify?

**Comment by c1gallagher** [comment]
Yes, the correct version is now posted.
